- id: emc-primary-controller
  role: ['primary-controller']
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/primary_controller.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
- id: emc-controller
  role: ['controller']
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/controller.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
- id: emc-compute
  role: ['compute']
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/compute.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
